# foundry.toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = [".env"]
remappings = [
    "@layerzerolabs/solidity-examples/=lib/solidity-examples/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solc = "0.8.20"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimism_sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }